version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/nodejs/Dockerfile
    container_name: bookion-app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - TOUR_API_KEY=${TOUR_API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - MYSQL_DB_HOST=mysql
      - MYSQL_DB_PORT=3306
      - MYSQL_DB_NAME=${MYSQL_DATABASE}
      - MYSQL_DB_USER=${MYSQL_USER}
      - MYSQL_DB_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bookion-network

  mysql:
    build:
      context: .
      dockerfile: ./dockerfiles/mysql/Dockerfile
    container_name: bookion-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dockerfiles/mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./dockerfiles/mysql/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookion-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: bookion-phpmyadmin
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${MYSQL_PORT}
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_ARBITRARY=1
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bookion-network

networks:
  bookion-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
